### ISSUE TITLE
Error Message on Start up

### ISSUE THREAD

**Issue by oddball250** [Benik/NutsAndBolts#2]
Hello, just come back to wow, with only Nuts and Bolts and Elvui on, im getting this error message, i noticed that it mention ACE 3.0 so tried adding that addon as well but got same message, any ideas?

Message: bad argument #3 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
Time: Sun Nov  6 18:01:21 2022
Count: 1
Stack: bad argument #3 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CreateFontString'
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:119: in function <...I_NutsAndBolts/modules/LocationLite/LocationLite.lua:105>
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:434: in function `Initialize'
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:454: in function <...I_NutsAndBolts/modules/LocationLite/LocationLite.lua:452>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1791: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1804: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1832: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1941: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:226: in function <Interface/AddOns/ElvUI/Core/init.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

**Comment by oddball250** [comment]
I also noticed, that despite Locationlite being enabled, all the option tabs inside of it are grayed out

**Comment by Benik** [comment]
Regarding Ace3, it's a library that is used by addons and it's included on every addon, ElvUI included. Reinstalling ElvUI (currently in v12.99) will solve your issue. Remember to delete ElvUI and ElvUI_Options folders prior updating, while not in game. You will not lose your settings.
As for LocationLite options being grayed out, you probably have LocationPlus installed. There is a button in LocationLite options, that disables LocationPlus. There is also a message there regarding the grayed out options :)

**Comment by oddball250** [comment]
hi, uninstalled Elvui, and manually reinstalled it from Tukui, made it so the only two mods i had enabled with Nuts and bolts and Elvui. still got this, also dont have location plus installed

Message: bad argument #3 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
Time: Mon Nov  7 19:24:05 2022
Count: 1
Stack: bad argument #3 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CreateFontString'
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:119: in function <...I_NutsAndBolts/modules/LocationLite/LocationLite.lua:105>
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:434: in function `Initialize'
[string "@Interface/AddOns/ElvUI_NutsAndBolts/modules/LocationLite/LocationLite.lua"]:454: in function <...I_NutsAndBolts/modules/LocationLite/LocationLite.lua:452>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1791: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1804: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1832: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1941: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:226: in function <Interface/AddOns/ElvUI/Core/init.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

![Screenshot (58)](https://user-images.githubusercontent.com/597204/200396763-3c6b60ee-20d0-4df9-ad49-3642e6a4d702.png)
![Screenshot (59)](https://user-images.githubusercontent.com/597204/200396780-476d0e35-fb3c-4870-8360-daf8f22b19cc.png)

**Comment by Benik** [comment]
Should be fixed in v1.34
Thank you :)
